[tool.poetry]
name = "data-wrangler"
version = "0.1.0"
description = ""
authors = ["felix Gutierrez <felixvidalgu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
